name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: jakzal/phpqa:php7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test echo
        run: echo "valider"